### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by mattfarina** [sdboyer/gliph#1]
I can haz license plz.

**Comment by sdboyer** [comment]
MIT, as indicated by the README and in the composer.json. i do need to add a LICENSE file, though.

**Comment by remicollet** [comment]
Common licenses that require including their texts with all derivative works include ASL 2.0, EPL, BSD and MIT.

So yes, please, add the LICENSE file.

**Comment by remicollet** [comment]
Notice: this will be a blocker for this package to be included in any linux distribution, so this will block review for Fedora official repository https://bugzilla.redhat.com/1022644

**Comment by sdboyer** [comment]
yerp. done.

**Comment by remicollet** [comment]
Thanks :)

**Comment by sdboyer** [comment]
inclusion in fedora repos? haha, nifty! :+1:

gives me some nice motivation to keep knocking down things off that TODO list. i've been very focused on some other problems for the past couple weeks, but i'll probably binge on this again soon...

**Comment by siwinski** [comment]
FYI: I will be the maintainer for the Fedora package and I am doing so because this package is being used by Drupal 8.

**Comment by sdboyer** [comment]
ahhh, gotcha. now this all makes sense.

well, the project is still in very early stages. as the TODOs indicate,
lots more to come. however, i'm only really planning on API breakages
when we make the shift to PHP 5.5.
