### ISSUE TITLE
TraversableSplOs Implementation buggy

### ISSUE THREAD

**Issue by ircmaxell** [sdboyer/gliph#13]
Currently, in AdjacencyList, you detach the incorrect iterator from the stack. This leads to iterator state confusion with nested loops. The correct implementations should be:

```
public function eachVertex() {
    $set = $this->getTraversableSplos($this->vertices);
    foreach ($set as $vertex) {
        $adjacent = $set->getInfo();
        yield $vertex => $adjacent;
    }
    $this->walking->detach($set);
}
```

Note that it's detaching the set, as opposed to `$this->vertices` as it's presently implemented.

A similar refactor needs to occur with `eachAdjacent()` and `eachEdge()` (in DirectedAdjacencyList).

Thanks!

**Comment by sdboyer** [comment]
i don't _think_ this should be an issue, and the tests pass...which might just mean that i wrote tests which explore the problem insufficiently.

the way that i wrote this, the intention was that the first time a given splos is traversed and `$this->getTraversableSplos()` is called, it is stored into the `$this->walking`, and on subsequent times a clone is returned, but not stored in `$this->walking`. probably a silly 'optimization' (i was thinking stack vs heap allocations, but i have no idea if/how that works in php) that just makes the code harder to read, but the primary goal there was just to ensure that:
- we don't clone on the first iteration through
- we never bother tracking clones in `$this->walking`; this makes clones inherently ephemeral

i may well have thought it through incorrectly, though - are you noticing iterator state confusion? is there something we can add to the tests that will cover your case?

**Comment by sdboyer** [comment]
and, to be clear, yes, the `detach()` call is always called on the original splos, which in the case that a clone was iterated....oh shit. i see the problem :)
