### ISSUE TITLE
PSR coding standard

### ISSUE THREAD

**Issue by lyrixx** [sdboyer/gliph#20]
Hello.

I noticed your lib does not follow PSR CS. It's not a big deal, but will you accept a PR to fix it?

**Comment by sdboyer** [comment]
i believe it's consistent with PSR-0, just not PSR-4. but yeah, i'm totally fine with a PR to get it fully fixed up for PSR-4 compliance.

**Comment by sdboyer** [comment]
as i'm gearing up for v1 release soon, i'd love it if you could get the PR up for full PSR-4 compliance.

**Comment by lyrixx** [comment]
Sorry, I have no time anymore for that.

**Comment by sdboyer** [comment]
np, thanks
